src/components/CreateRoom.tsx, src/components/Dropdown.tsx, src/stories/createRoom.stories.tsx, src/stories/dropdown.stories.tsx
Implementación de la interfaz del componente **CreateRoom**
**Dropdown** confeccionado en base al elemento **select**, el funcionamiento de este componente es básicamente similar al de los RadioButton, a cada elemento se le puede pasar un:
- **label**: _Texto que mostrará al usuario_
- **value**: _Valor que contendrá para casos de formularios._
- **onClick**: _Para implementar alguna lógica al seleccionarlo._
Quedo a la espera de sus opiniones.
=> feat: Create `CreateRoom` modal content component

.eslintrc.json, .github/CODEOWNERS, commitlint.config.ts, src/components/Avatar.tsx, src/components/ChatContainer.tsx, src/components/ImageMessage.tsx, src/components/MessageContainer.tsx, src/components/Navigation.tsx, src/components/RadioGroup.tsx, src/components/Roster.tsx, src/components/ServerListItem.tsx, src/components/TextMessage.tsx, src/components/TypingIndicator.tsx, src/components/UnreadIndicator.tsx, src/components/UserProfile.tsx, src/hooks/matrix/useActiveRoom.ts, src/utils/util.ts
1. Optimicé la función de normalizar nombres para que use filter 
2. Revise en que casos de uso la key debería usar index, y en que otros debería ser algo mas único.
3. Respecto a la función getImage en lugar de retornar undefined cuando no obtiene la imagen, ahora retorna null, ya que null conviene más por su significado de ausencia de un valor.
=> refactor: General code improvement

src/components/CreateRoom.tsx, src/components/Navigation.tsx, src/utils/util.ts
Utilizando el componente `Create Room` en este PR hacemos la funcionalidad de creación de Rooms.
=> feat: Implement room creation functionality

src/components/WelcomChatContainer.tsx, src/stories/welcomChatContainer.stories.tsx
Componente WelcomChatContainer para mostrar en el ChatContainer cuando se inicie sesión y no halla ninguna ROOM seleccionada.
=> feat: Implement `WelcomeChatContainer` component

src/components/ChatContainerLoader.tsx, src/stories/chatContainerLoader.stories.tsx
Ya pueden revisar el componente ChatContainerLoader, quedo a la espera de sus sugerencias, les dejo una captura de como quedó aquí, por ahora es estático, o sea siempre se verá así.
=> feat: Add loader for `ChatContainer`

.github/workflows/build.yml, .github/workflows/deploy-push-master.yml, .github/workflows/eslint-action.yml, .github/workflows/prettier.yml
=> fix: Implement `node-version` for github actions

src/components/ProgressBar.tsx, src/stories/progressBar.stories.tsx, src/styles/tailwind.css, tailwind.config.ts
* Implemente `LinearProgressBar` para una barra de progreso.
* Implemente `CircleProgressBar` para una barra de progreso en forma de circulo.
* Implemente el componente `ProgressBar` que elige dependiendo de la variante.
El progress bar de forma global tiene 3 estados:
1. Progress: Es el estado en el cual esta cargando o rellenandose la barrita.
2. Completed: Es el estado completado donde se marca con color verde, (llego a 100%)
3. Error: Es el estado por si ocurre un error en la carga mostrar visualmente.
El estado se gestiona con un `enum` llamado `ProgressBarState` de forma que se pueda usar en un `useState` de forma:
```ts
useState<ProgressBarState>()
// Ocurrio un problema en la subida
setState(ProgressBarState.Error)
```
De esa forma considero que sera mas facil para el …
=> feat: Implement `ProgressBar` component

src/components/CallModal.tsx, src/components/CreateRoomModal.tsx, src/components/DropdownActions.tsx, src/components/ServerDropdown.tsx, src/containers/NavigationSection/index.tsx, src/stories/dropdownActions.stories.tsx, src/stories/serverDropdown.stories.tsx, src/utils/util.ts, src/views/login.tsx
* Optimizar la funcion `stringToColor`.
* Solucionar problema del login.
Seleccionador de servidor puesto en el NavigationSection
=> fix: Fix login problems for `Button` state `disabled`

src/components/TypingIndicator.tsx, src/containers/RoomContainer/ChatContainer.tsx, src/containers/RoomContainer/hooks/useRoomChat.tsx, src/stories/typingIndicator.stories.tsx
=> feat: Implementation new `TypingIndicator` component

src/containers/RoomContainer/ChatContainer.tsx, src/containers/RoomContainer/ChatInput.tsx, src/containers/RoomContainer/useChatInput.ts, src/views/dev.tsx
=> feat: Implement new `ChatInput` component

package.json, src/components/EventMessage.tsx, src/containers/RoomContainer/ChatMessages.tsx, src/containers/RoomContainer/hooks/useRoomChat.tsx, src/utils/members.ts, src/utils/rooms.ts, src/views/dev.tsx, yarn.lock
=> feat: Implement new handling for ´EventMessage´

src/containers/RoomContainer/ChatMessages.tsx, src/utils/rooms.ts
=> fix: Solve positioning problem for `UnreadIndicator`

.github/workflows/commitlint-pr.yml, .husky/commit-msg, .husky/pre-commit
=> chore: Implement PR title checker

src/components/AudioMessage.tsx, src/components/AvatarImage.tsx, src/components/Button.tsx, src/components/CallModal.tsx, src/components/Checkbox.tsx, src/components/ContextMenu.tsx, src/components/Detail.tsx, src/components/Dropdown.tsx, src/components/DropdownActions.tsx, src/components/EmojiPicker.tsx, src/components/EventMessage.tsx, src/components/FileMessage.tsx, src/components/ImageMessage.tsx, src/components/ImageZoom.tsx, src/components/InputSection.tsx, src/components/Label.tsx, src/components/Loader.tsx, src/components/MessageContainer.tsx, src/components/Modal.tsx, src/components/Notification.tsx, src/components/RadioButton.tsx, src/components/Room.tsx, src/components/SmartAction.tsx, src/components/StatusMessage.tsx, src/components/SwitchButton.tsx, src/components/TextMessage.tsx, src/components/UnreadIndicator.tsx, src/components/UserProfile.tsx, src/components/UserProfileGhost.tsx, src/utils/util.ts
=> feat: Implement more `assert` for components

src/components/AudioMessage.tsx, src/components/AvatarImage.tsx, src/components/FileMessage.tsx, src/components/ImageMessage.tsx, src/components/MessageContainer.tsx, src/components/TextMessage.tsx, src/containers/RoomContainer/ChatMessages.tsx, src/utils/rooms.ts
=> feat: Update `MessageContainer` component

package.json, src/components/ContextMenu.tsx, src/components/Detail.tsx, src/components/Dropdown.tsx, src/components/IconButton.tsx, src/components/Modal.tsx, src/components/Room.tsx, src/components/UserProfileGhost.tsx, src/containers/NavigationSection/RoomList.tsx, src/containers/NavigationSection/Space.tsx, src/containers/NavigationSection/Spaces.tsx, src/containers/NavigationSection/modals/DirectMessageModal.tsx, src/containers/NavigationSection/modals/NotificationBoxPopup.tsx, src/containers/RoomContainer/ChatContainer.tsx, src/containers/RoomContainer/ChatMessages.tsx, src/containers/RoomContainer/RoomContainer.tsx, src/containers/Roster/RosterUser.tsx, src/views/dev.tsx, yarn.lock
Haciendo estas animaciones me di cuenta que intentar hacer animaciones distintas sin seguir un patron de animacion da una experiencia rara, por eso trate de seguir un mismo patron, sin dejar de probar en cada animacion nueva una animacion distinta haber si pegaba.
=> feat: Implement FramerMotion for performance

src/utils/util.ts
=> feat: Update `stringToColor` function

.github/pull_request_template.md, .vscode/settings.json, netlify.toml, package.json, src/components/Button.tsx, src/components/CallModal.tsx, src/components/Checkbox.tsx, src/components/Detail.tsx, src/components/DropdownActions.tsx, src/components/EmojiPicker.tsx, src/components/EventMessage.tsx, src/components/FileMessage.tsx, src/components/InputSection.tsx, src/components/Label.tsx, src/components/Loader.tsx, src/components/MessageContainer.tsx, src/components/Modal.tsx, src/components/RadioButton.tsx, src/components/Room.tsx, src/components/SmartAction.tsx, src/components/UserProfile.tsx, src/containers/RoomContainer/ChatHeader.tsx, src/containers/RoomContainer/hooks/useRoomChat.tsx, src/utils/util.ts
=> feat: Update PR template

src/components/VideoMessage.tsx, src/containers/RoomContainer/ChatMessages.tsx, src/containers/RoomContainer/hooks/useRoomChat.tsx, src/stories/Chat/fileMessage.stories.tsx, src/stories/Chat/videoMessage.stories.tsx, src/utils/rooms.ts
Esto permitirá procesar mensajes con vídeos en el Chat
=> feat: Implement Video Message

src/components/ImagePreview.tsx, src/containers/RoomContainer/ImageModalPreview.tsx, src/stories/imagePreview.stories.tsx
=> feat: Update `ImagePreview` component

src/components/Button.tsx, src/components/FileMessage.tsx, src/components/FilePreview.tsx, src/stories/filePreview.stories.tsx, src/utils/util.ts, src/views/login.tsx
- Se implementa modal para enviar archivos en Matrix. 
- Se implementa función para enviar archivos en Matrix. 
- Extra: Se mejoró el diseño del Componente Button. 
- Extra: Se mejoró el diseño del Button en el Login
=> feat: implement file preview

src/components/AudioFilePreview.tsx, src/components/AudioPreview.tsx, src/stories/audioPreview.stories.tsx, src/utils/util.ts
=> feat: implement AudioFilePreview

.github/pull_request_template.md, src/components/ContextMenu.tsx, src/components/Modal.tsx, src/components/Room.tsx, src/containers/NavigationSection/Space.tsx, src/containers/RoomContainer/ChatContainer.tsx, src/containers/RoomContainer/ChatInput.tsx, src/containers/Roster/RosterUser.tsx
=> fix: Fix `ChatInput` problems

src/containers/RoomContainer/hooks/useRoomChat.tsx, yarn.lock
- Ahora cuando pasa un determinado tiempo en el chat se quita automaticamente el indicador
- Si envias un mensaje en el chat no se vera el indicador, y si el indicador esta activo se quitara automaticamente cuando envies un mensaje
=> feat: Implement new `UnreadIndicator` handling

package.json, public/icons/clear-search-icon-dark.svg, public/icons/clear-search-icon.svg, src/components/EmojiPicker.tsx, src/components/Input.tsx, src/components/ui/button.tsx, src/components/ui/input.tsx, src/components/ui/scroll-area.tsx, src/components/ui/toggle-group.tsx, src/containers/RoomContainer/ChatInput.tsx, src/hooks/util/useEmojiPicker.ts, src/hooks/util/useEmojiSearch.ts, src/hooks/util/useLocalStorage.ts, src/lang/english.ts, src/lang/spanish.ts, src/styles/tailwind.css, src/utils/util.ts, src/views/dev.tsx, tailwind.config.ts, yarn.lock
En este PR tambien se implemento el Input de shadcn, en shadcn el input es un componente que no esta muy bien gestionado por lo cual yo mismo tuve que hacer varias modificaciones y mejoras para que se adaptara a nuestro uso. Tambien tuve que implementar accesibilidad y modo oscuro para el componente Input
Modo Oscuro =>
Modo Light =>
=> feat: Update UI for `EmojiPicker` component

src/components/ui/alert-dialog.tsx, src/components/ui/modal.tsx, src/stories/modal.stories.tsx, src/styles/tailwind.css, src/views/dev.tsx, tailwind.config.ts
=> feat: Implement new `Modal` component

src/components/ui/input.tsx, src/views/login.tsx
=> feat: implement resposive login

src/containers/NavigationSection/NavigationSection.tsx, src/containers/NavigationSection/SidebarActions.tsx, src/lang/allKeys.ts, src/lang/english.ts, src/lang/spanish.ts, src/views/app.tsx
=> feat: Implement `log out` button

src/components/ui/button.tsx, src/containers/NavigationSection/RoomNavigator.tsx, src/containers/NavigationSection/UserBar.tsx
Estado Dark =>
Estado Error =>
Estado Cargando =>
Estado Cargado =>
=> feat: Improve `UserBar` component

src/components/SmartActionBar.tsx
=> feat: Implement dark mode function

.vscode/lkey.code-snippets, package.json, src/components/AvatarUploader.tsx, src/components/CreateSpaceModal.tsx, src/components/ui/toast.tsx, src/components/ui/toaster.tsx, src/containers/NavigationSection/NavigationSection.tsx, src/containers/NavigationSection/SpacesNavigation.tsx, src/containers/NavigationSection/hooks/useSpaces.ts, src/hooks/use-toast.ts, src/hooks/util/useFilePicker.ts, src/index.tsx, src/lang/allKeys.ts, src/lang/english.ts, src/lang/spanish.ts, src/utils/util.ts, src/views/dev.tsx, yarn.lock
=> feat: Improve `CreateSpaceModal` component

src/components/ui/input.tsx, src/lang/english.ts, src/views/login.tsx
=> fix: Small design improvements

package.json, src/containers/NavigationSection/DMTrayPopup.tsx, src/containers/NavigationSection/SidebarActions.tsx, src/containers/RoomContainer/RoomInvitedSplash.tsx, src/hooks/util/useMediaQuery.ts, src/lang/allKeys.ts, src/lang/english.ts, src/lang/spanish.ts, src/utils/rooms.ts
- Se implemento la obtención de usuario a partir de la búsqueda
- Se implemento el click de un usuario de resultado de búsqueda para que salga un Modal con la posibilidad de crear una conversación.
- Se implemento la lógica para la creación de la conversación.
=> feat: Implement direct chats creation handling
